blog/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('', PostView.as_view(), name='PostList'),
    path('category/<int:cat_id>/', PostCategoryView.as_view(), name='PostListCategory'),
    path('detail/<slug:post_slug>/', PostDetail.as_view(), name='PostDetail'),
    path('update/<slug:post_slug>/', PostEdit.as_view(), name='PostEdit'),
    path('createpost/', AddPost.as_view(), name='AddPost'),
    path('createcategory/', AddCategory.as_view(), name='AddCategory'),
    path('register/', RegisterUser.as_view(), name='Register'),
    path('login/', LoginUser.as_view(), name='Login'),
    path('logout/', logOutUser, name='Logout'),
    path('movieList/', MovieList.as_view(), name='MovieList'),
    path('movieCategory/<int:genre_id>/', MovieCategoryView.as_view(), name='MovieCategory'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
import datetime
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator


def get_image_url(instance, filename):
    return 'Posts/images/{0}/{1}'.format(instance.user.username, filename)


class Post(models.Model):

    title = models.CharField(_('Название'), max_length=255,)
    slug = models.SlugField(_('URL-кодировка'))
    content = models.TextField(_('Содержание'), max_length=5000)
    photo = models.ImageField(_('Фото'), upload_to=get_image_url, null=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT, default=User)
    category = models.ForeignKey('Category', on_delete=models.PROTECT)
    time_create = models.DateTimeField(_('date_published'), auto_now_add=True)
    time_update = models.DateTimeField(_('date_update'), auto_now=True)
    is_published = models.BooleanField(_('Статус публикации'),default=True,)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('PostDetail', kwargs={'post_slug': self.slug})


class Category(models.Model):
    name = models.CharField(_('Название категории'), max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('PostListCategory', kwargs={'cat_id': self.id})


class Genre(models.Model):
    name = models.CharField(_('Жанр'), max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(_("Название"), max_length=255)
    slug = models.SlugField(_("URL"))
    content = models.TextField(_('Описание'),max_length=5000)
    photo = models.ImageField(upload_to='Movies/%Y/%M/%D')
    year = models.PositiveIntegerField(
        default=datetime.date.today().year, validators=[MinValueValidator(1984), MaxValueValidator(datetime.date.today().year)])
    country = models.CharField(_('Страна'), max_length=255)
    genre = models.ForeignKey(Genre, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT, default=User)
    time_create = models.DateTimeField(_('date_published'), auto_now_add=True)
    time_update = models.DateTimeField(_('date_update'), auto_now=True)
    is_published = models.BooleanField(_('Статус публикации'), default=True)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import *


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'


class AddCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control mr-0 ml-auto'}))
    email = forms.EmailField(label='Почта', widget=forms.EmailInput(attrs={'class': 'form-control mr-0 ml-auto'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control mr-0 ml-auto'}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-control mr-0 ml-auto'}))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')



class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control mr-0 ml-auto'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control mr-0 ml-auto'}))

blog/views.py
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .models import *
from .forms import *


class PostView(ListView):
    paginate_by = 2
    model = Post
    template_name = 'blog/PostList.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context



class PostCategoryView(ListView):
    paginate_by = 2
    model = Post
    template_name = 'blog/PostList.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        context['cat_id'] = self.kwargs['cat_id']
        return context

    def get_queryset(self):
        return Post.objects.filter(category_id=self.kwargs['cat_id'])


class PostDetail(DetailView):
    model = Post
    template_name = 'blog/PostDetail.html'
    slug_url_kwarg = 'post_slug'


class AddPost(CreateView):
    form_class = AddPostForm
    template_name = 'blog/PostCreate.html'
    success_url = reverse_lazy('PostList')


class PostEdit(UpdateView):
    model = Post
    template_name = 'blog/PostCreate.html'
    success_url = reverse_lazy('PostList')
    slug_url_kwarg = 'post_slug'
    fields = '__all__'


class AddCategory(CreateView):
    form_class = AddCategoryForm
    template_name = 'blog/CreateCategory.html'
    success_url = reverse_lazy('PostList')


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'blog/Register.html'
    success_url = reverse_lazy('PostList')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'blog/Login.html'

    def get_success_url(self):
        return reverse_lazy('PostList')


def logOutUser(request):
    logout(request)
    return redirect('Login')


class MovieList(ListView):
    model = Movie
    template_name = 'blog/MovieList.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genre'] = Genre.objects.all()
        return context


class MovieCategoryView(ListView):
    model = Movie
    template_name = 'blog/MovieList.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genre'] = Genre.objects.all()
        return context

    def get_queryset(self):
        return Movie.objects.filter(genre_id=self.kwargs['genre_id'])

blog/templates/blog/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Главная страница
    {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'blog/fontawesome/css/all.min.css' %}"> <!-- https://fontawesome.com/ -->
	<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet"> <!-- https://fonts.google.com/ -->
    <link href="{% static 'blog/css/templatemo-xtra-blog.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>

	<header class="tm-header" id="tm-header">
        <div class="tm-header-wrapper">
            <button class="navbar-toggler" type="button" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="tm-site-header">
                <div class="mb-3 mx-auto tm-site-logo"><i class="fab fa-vaadin fa-2x"></i></div>
                <h1 class="text-center">Taurus Blog</h1>
                {% if user.is_authenticated %}
                    <h3 class="text-center">
                    Здравствуй {{ user.username }}
                    </h3>
                {% endif %} 
            </div>

            <nav class="tm-nav" id="tm-nav">
                <ul>
                    <li class="tm-nav-item active"><a href="{% url 'PostList' %}" class="tm-nav-link">
                        <i class="fas fa-home"></i>
                        Главная страница
                    </a></li>

                    <li class="tm-nav-item dropdown">
                    <a class="tm-nav-link" href="{% url 'PostList' %}">
                      <i class="fas fa-envelope-open-text"></i>
                        Все категории
                    </a>
                    <div class="dropdown-menu tm-nav-item" aria-labelledby="navbarDropdown">
                        {% for cat in category %}
                            <a class="dropdown-item tm-nav-link" href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
                        {% endfor %}
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'AddCategory' %}" class = "dropdown-item tm-nav-link">
                            Добавить категорию
                        </a>
                    </div>

                  </li>

                    <li class="tm-nav-item"><a href="{% url 'AddPost' %}" class="tm-nav-link">
                        <i class="fas fa-pen"></i>
                        Добавить статью
                    </a></li>
                    <li class="tm-nav-item"><a href="about.html" class="tm-nav-link">
                        <i class="fas fa-users"></i>
                        Личный кабинет
                    </a></li>
                    <li class="tm-nav-item"><a href="{% url 'MovieList' %}" class="tm-nav-link">
                        <i class="fas fa-camera-retro"></i>
                        Кинотеатр
                    </a></li>
                </ul>
                <form method="GET" class="form-inline tm-mb-80 tm-search-form">
                    <input class="form-control tm-search-input" name="query" type="text" placeholder="Найти..." aria-label="Search">
                    <button class="tm-search-button" type="submit">
                        <i class="fas fa-search tm-search-icon" aria-hidden="true"></i>
                    </button>
                </form>
            </nav>
{#            <div class="tm-mb-65">#}
{#                <a rel="nofollow" href="https://fb.com/templatemo" class="tm-social-link">#}
{#                    <i class="fab fa-facebook tm-social-icon"></i>#}
{#                </a>#}
{#                <a href="https://twitter.com" class="tm-social-link">#}
{#                    <i class="fab fa-twitter tm-social-icon"></i>#}
{#                </a>#}
{#                <a href="https://instagram.com" class="tm-social-link">#}
{#                    <i class="fab fa-instagram tm-social-icon"></i>#}
{#                </a>#}
{#                <a href="https://linkedin.com" class="tm-social-link">#}
{#                    <i class="fab fa-linkedin tm-social-icon"></i>#}
{#                </a>#}
{#            </div>#}
        </div>
    </header>
    <div class="container-fluid">
        <main class="tm-main">
            <div class="row tm-row">
            <div class="col-12">
            <div class="tm-mb-65 login-buttons ">
                {% if user.is_authenticated %}
                    <a href="{% url 'Logout' %}" class="mb-2 tm-btn tm-btn-primary tm-bg-gray tm-mr-15 tm-color-primary">Выйти</a>
                {% else %}
                    <a href="{% url 'Login' %}" class="mb-2 tm-btn tm-btn-primary tm-bg-gray tm-mr-15 tm-color-primary">Войти</a>
                    <a href="{% url 'Register' %}" class="mb-2 tm-btn tm-btn-primary tm-bg-gray tm-mr-15 tm-color-primary">Регистрация</a>
                {% endif %}
            </div>
                    {% for cat in category %}
                        {% if cat.id == cat_id %}
                            <h1>{{ cat.name }}</h1>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="row tm-row">
                {% block content %}
                
                {% endblock %}
            </div>
{#            Пагинатор#}


            <div class="row tm-row tm-mt-100 tm-mb-75">
            {% if page_obj %}
                <div class="tm-prev-next-wrapper">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}" class="mb-2 tm-btn tm-btn-primary tm-prev-next tm-mr-20">Назад</a>
                    {% else %}
                        <a class="mb-2 tm-btn tm-btn-primary tm-prev-next disabled tm-mr-20">Назад</a>
                    {% endif %}
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}" class="mb-2 tm-btn tm-btn-primary tm-prev-next">Далее</a>
                    {% else %}
                        <a class="mb-2 tm-btn tm-btn-primary disabled tm-prev-next">Далее</a>
                    {% endif %}
                </div>
             {% endif %}
                <div class="tm-paging-wrapper">
                    <nav class="tm-paging-nav d-inline-block">
                        <ul>
                            {% for p in paginator.page_range %}
                            <li class="tm-paging-item active">
                            {% if page_obj.number >= p|add:-1 and page_obj.number <= p|add:1 %}


                                {% if page_obj.number == p %}
                                    <a href="?page={{ p }}" class="mb-2 tm-btn-small tm-color-primary">{{ p }}</a>
                                {% else %}
                                    <a href="?page={{ p }}" class="mb-2 tm-btn tm-paging-link">{{ p }}</a>
                                {% endif %}
                            {% endif %}
                            </li>
                            {% endfor %}

                        </ul>
                    </nav>
                </div>
            </div>
            <footer class="row tm-row">
                <hr class="col-12">
                <div class="col-md-6 col-12 tm-color-gray">
                    Design: <a rel="nofollow" target="_parent" href="https://templatemo.com" class="tm-external-link">TemplateMo</a>
                </div>
                <div class="col-md-6 col-12 tm-color-gray tm-copyright">
                    Copyright 2020 Xtra Blog Company Co. Ltd.
                </div>
            </footer>
        </main>
    </div>

    <script src="{% static 'blog/js/jquery.min.js' %}"></script>
    <script src="{% static 'blog/js/templatemo-script.js' %}"></script>
</body>
</html>

blog/templates/blog/CreateCategory.html
{% extends 'blog/Base.html' %}

{% block title %}
        Добавить Категорию
{% endblock %}

{% block content %}
    <form action="{% url 'AddCategory' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for i in form %}
            <div class="form-group row mb-4">
                <label for="{{ i.label }}" class="col-sm-3 col-form-label text-right tm-color-primary">{{ i.label }}</label>
                <div class="col-sm-9">
                    {{ i }}
                </div>
            </div>
        {% endfor %}
        <div class="form-group row text-right">
            <div class="col-12">
                <button class="tm-btn tm-btn-primary tm-btn-small">Создать</button>
            </div>
        </div>
    </form>

{% endblock %}

blog/templates/blog/Login.html
{% extends 'blog/Base.html' %}


{% block title %}
    Авторизация
{% endblock %}

{% block content %}
            <form action="{% url 'Login' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for i in form %}
            <div class="form-group row mb-4">
                <label for="{{ i.label }}" class="col-sm-3 col-form-label text-right tm-color-primary">{{ i.label }}</label>
                <div class="col-sm-9">
                    {{ i }}
                </div>
            </div>
        {% endfor %}
        <div class="form-group row text-right">
            <div class="col-12">
                <button class="tm-btn tm-btn-primary tm-btn-small">Войти</button>
            </div>
        </div>
    </form>
{% endblock %}

blog/templates/blog/MovieList.html
{% extends 'blog/Base.html' %}


{% block title %}
    Кинотеатр
{% endblock %}

{% block content %}
    <div class="row tm-row">
    <h3>Жанры</h3>
    {% for gen in genre %}
        <a href="{% url 'MovieCategory' genre_id=gen.id %}"  class="mb-2 tm-btn tm-btn-primary tm-bg-gray tm-mr-15 tm-color-primary w-25">
            {{ gen.name }}
        </a>
    {% endfor %}
    </div>


    {% for movie in movie_list %}
        <article class="col-12 col-md-6 tm-post">
            <hr class="tm-hr-primary">
            <a href="#" class="effect-lily tm-post-link tm-pt-60">
                <div class="">
                    <img src="{{ movie.photo.url }}" alt="Image" class="img-fluid w-50">
                </div>
                <span class="position-absolute tm-new-badge">{{ movie.genre }}</span>
                <h2 class="tm-pt-30 tm-color-primary tm-post-title">{{ movie.title }}</h2>
            </a>
            <p class="tm-pt-30">
                {{ movie.content|truncatewords:20 }}
            </p>
            <div class="d-flex justify-content-between tm-pt-45">
                <span class="tm-color-primary">{{ movie.year }}</span>
                <span class="tm-color-primary">{{ post.time_create }}</span>
            </div>
            <hr>
            <div class="d-flex justify-content-between">
                <span>Автор: {{ movie.user.username }}</span> <span><a href="#">Редактировать</a></span>
            </div>
        </article>
    {% endfor %}
{% endblock %}

blog/templates/blog/PostCreate.html
{% extends 'blog/Base.html' %}

{% block title %}
    Добавить статью
{% endblock %}

{% block content %}
    <form action="{% url 'AddPost' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
{#        {{ form.as_p }}#}
        {% for i in form %}
            <div class="form-group row mb-4">
                <label for="{{ i.label }}" class="col-sm-3 col-form-label text-right tm-color-primary">{{ i.label }}</label>
                <div class="col-sm-9">
                    {{ i }}
                </div>
            </div>
        {% endfor %}
        <div class="form-group row text-right">
            <div class="col-12">
                <button class="tm-btn tm-btn-primary tm-btn-small">Создать</button>
            </div>
        </div>
    </form>


{% endblock %}

blog/templates/blog/PostDetail.html
{% extends 'blog/Base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}


<div class="row tm-row tm-mb-45">
                <div class="col-12">
                    <hr class="tm-hr-primary tm-mb-55">
                    <img src="{{ post.photo.url }}" alt="Image" class="img-fluid">
                </div>
            </div>
            <div class="row tm-row tm-mb-40">
                <div class="col-12">
                    <div class="mb-4">
                        <h2 class="pt-2 tm-mb-40 tm-color-primary tm-post-title">{{ post.title }}</h2>
                        <p>
                           {{ post.content }}
                        </p>
                    </div>
                </div>
            </div>
{% endblock %}

blog/templates/blog/PostList.html
{% extends 'blog/Base.html' %}

{% block title %}
    Главная страница
{% endblock %}

{% block content %}
    {% for post in post_list %}
        <article class="col-12 col-md-6 tm-post">
            <hr class="tm-hr-primary">
            <a href="{{ post.get_absolute_url }}" class="effect-lily tm-post-link tm-pt-60">
                <div class="tm-post-link-inner">
                    <img src="{{ post.photo.url }}" alt="Image" class="img-fluid">
                </div>
                <span class="position-absolute tm-new-badge">Новинка</span>
                <h2 class="tm-pt-30 tm-color-primary tm-post-title">{{ post.title }}</h2>
            </a>
            <p class="tm-pt-30">
                {{ post.content|truncatewords:20 }}
            </p>
            <div class="d-flex justify-content-between tm-pt-45">
                <span class="tm-color-primary">{{ post.category }}</span>
                <span class="tm-color-primary">{{ post.time_create }}</span>
            </div>
            <hr>
            <div class="d-flex justify-content-between">
                <span>Автор: {{ post.user.username }}</span> <span><a href="{% url 'PostEdit' post_slug=post.slug %}">Редактировать</a></span>
            </div>
        </article>
    {% endfor %}
{% endblock %}

blog/templates/blog/Register.html
{% extends 'blog/Base.html' %}

{% block title %}
    Регистрация
{% endblock %}

{% block content %}
        <form action="{% url 'Register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for i in form %}
            <div class="form-group row mb-4">
                <label for="{{ i.label }}" class="col-sm-3 col-form-label text-right tm-color-primary">{{ i.label }}</label>
                <div class="col-sm-9">
                    {{ i }}
                </div>
            </div>
        {% endfor %}
        <div class="form-group row text-right">
            <div class="col-12">
                <button class="tm-btn tm-btn-primary tm-btn-small">Регистрация</button>
            </div>
        </div>
    </form>
{% endblock %}